name: example_rabbit

# Описываем секреты, которые будут доступны в сервисах в папке /run/secrets/
services:
  rabbit_queue:
    container_name: example_rabbit_queue
    hostname: example_rabbit_queue
    image: rabbitmq:4-management
    restart: always
    shm_size: 128mb # Shared memory limit when using docker-compose
    ports:
      # exposed:internal
      - 5672:5672
      - 15672:15672
    networks:
      - gmike_network

  rabbit_api:
    build:
      dockerfile: Dockerfile
      context: ..
    container_name: example_rabbit_api
    hostname: example_rabbit_api
    image: example_rabbit_api
    restart: always
    shm_size: 128mb # Shared memory limit when using docker-compose
    ports:
      # exposed:internal
      - 5185:80
    environment:
      ASPNETCORE_URLS: http://+:80
      RABBITMQ__HOST: $RABBITMQ__HOST
      RABBITMQ__PORT: $RABBITMQ__PORT
    networks:
      - gmike_network

networks:
  gmike_network:
    name: gmike_network
    external: true
